--- 
- hosts: localhost
- import_playbook: next_ip.yaml
- gather_facts: false
  hosts: localhost
  roles: 
    - syncrou.manageiq-automate
  tasks: 
    - debug: 
        msg: "{{ result.ansible_facts.ipaddr }}"
    - debug: 
        var: miq_provision_id
    - debug: 
        var: miq_provision_request_id
    - name: "update task with new IP and hostname information"
      uri: 
        body: 
          action: edit
          resource: 
            options: 
              addr_mode: static
              ip_addr: "{{ result.ansible_facts.ipaddr }}"
              subnet_mask: "{{ netmask }}"
        body_format: json
        headers: 
          X-Auth-Token: "{{ manageiq.api_token }}"
        method: POST
        status_code: 200
        url: "{{ manageiq.api_url }}/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
        validate_certs: false
    - manageiq_automate: 
      name: "Save the job ID back into $evm.root"
      set_attribute: 
        attribute: ip_addr
        object: root
        value: "{{ ip_addr }}"
      workspace: "{{ workspace }}"
  vars: 
    - 
      netmask: "255.255.255.0"
