---
- hosts: localhost
- import_playbook: next_ip.yaml

- hosts: localhost
  gather_facts: no
  vars:
    - netmask: 255.255.255.0
  roles:
  - syncrou.manageiq-automate
  tasks:
    - debug: 
        msg: "{{ result.ansible_facts.ipaddr }}" 
    - debug:
        var: miq_provision_id
    - debug:
        var: miq_provision_request_id
    - name: update task with new IP and hostname information
      uri:
        url: "{{ manageiq.api_url }}/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
        method: POST
        body_format: json
        body:
          action: edit
          resource:
            options:
              addr_mode: "static"
              ip_addr: "{{ result.ansible_facts.ipaddr }}"
              subnet_mask: "{{ netmask }}"
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
        body_format: json
        status_code: 200
   - name: "Save the job ID back into $evm.root"
     manageiq_automate:
      workspace: "{{ workspace }}"
      set_attribute:
        object: "root"
        attribute: "ip_addr"
        value:  "{{ ip_addr }}"

