---
- hosts: localhost
- import_playbook: next_ip.yaml

- hosts: localhost
  gather_facts: no
  vars:
    - netmask: 24
  tasks:
    - debug:
        var: miq_provision_id
    - debug:
        var: miq_provision_request_id
    - name: update task with new IP and hostname information
      uri:
        url: "{{ manageiq.api_url }}/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
        method: POST
        body_format: json
        body:
          action: edit
          resource:
            options:
              addr_mode: ["static", "Static"]
              ip_addr: "{{ result.ansible_facts.ipaddr }}"
              subnet_mask: "{{ netmask }}"
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
        body_format: json
        status_code: 200

