---
- name: Nios_Host_Record
  hosts: localhost
  connection: local
  roles:
    - syncrou.manageiq-automate
  vars_files: /vars/host.yaml
  tasks:
  - name: "Get Attributes"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_state_var:
        attribute: ip_addr
    register: ip_addr
  - debug:
      msg: "First item: {{ ip_addr['value'][0] }}"
  - name: Create Nios Host_Record
    nios_host_record:
      name: neha-host.ansible.com
      ipv4:
      - address: "{{ ip_addr['value'][0] }}"
      state: present
      comment: ip address added
      provider: "{{ nios_provider }}"                                 
    register: host_created
